### ISSUE TITLE
Can't "Execute Selected Lua" containing MoonSharp's "short anonymous functions"

### ISSUE THREAD

**Issue by Benjamin-Dobell** [Berserk-Games/atom-tabletopsimulator-lua#103]
Presumably just to keep us on our toes, MoonSharp was implemented with one syntactical addition over regular Lua. These come in the form of [short anonymous functions](https://www.moonsharp.org/moonluadifferences.html).

Given this is non-standard Lua syntax, anything expecting standard Lua syntax is going to have a hard time.

In terms of this extension, this most obviously manifests itself when you try select some Lua contained within a `.ttslua` file that utilises the aforemented syntax, and try execute it within TTS.

e.g.

```lua
    function manipulate(x, manipulator)
        return manipulator(x)
    end
    print(manipulate(2, |x| x * x))
```

Gives the error:

> **Invalid Lua selection:**
> [4:24] \<expression\> expected near '|'

This will of course work if the short anonymous function were changed to the 100% equivalent syntax:

```lua
    function manipulate(x, manipulator)
        return manipulator(x)
    end
    print(manipulate(2, function(x) return x * x end))
```

## Demonstration

![short anonymous functions](https://user-images.githubusercontent.com/482276/72815571-f62dc600-3cba-11ea-9cad-badb8d7237c4.gif)

## Fix

I'm already working on a solution and will submit a PR for review shortly.

**Comment by onelivesleft** [comment]
I was thinking about a feature recently, which I hadn't come to any conclusions over, but whose implementation would generalise this issue.  The idea would be to have an extended syntax, so that you could, for instance, do `foo += 1`, which would convert when sending to TTS into `foo = foo + 1`.  This could just be for some hard-coded permutations such as this family of operators, `foo++` etc, or extended to allow user some kind of user `#define`.  

To be able to go back and forth would be handled like `#include` does, by adding comments of the transformed code.  So, the above example would be sent to tts as two lines:
```
foo = foo + 1 --macro
--foo += 1
```
The comment can be interpreted by the plugin to reverse the operation when loading from TTS.

Obviously, given this setup your `|x|` syntax can easily be transformed into `function(x)` syntax.

The question is, is this a desirable feature?  Or is it too crufty?  What do you think?

**Comment by Benjamin-Dobell** [comment]
I'm actually not at all a fan of MoonSharp having added this syntax; it's not that I don't like the syntax, I do; it's just that I don't really think the VM is the place for these sorts of additions.

_However_, I have zero issue with code transpilation as a "build step", this sort of stuff can be really powerful. Of course, as you know, the issue we have that other transpilers don't, is that we need to preserve the original syntax somehow, such that the transpilation can take place in reverse.

Additionally, transpilers tend to operate on an AST. Even the seemingly simple `+=` can become complicated if we run into something like:

```lua
local var = 1
x += (function()
    var += 1
    return var
end)()
```

Whilst, I think you'd be well within your right to slap anyone who genuinely writes the above, it's these sorts of edge cases that can really seemingly simple little syntax additions up.

To do this safely, you really need to do so at the AST level. This is actually what I'm doing for short anonymous functions, I've forked `luaparse` and have added appropriate lexing and am finishing of the parsing right now.

Because MoonSharp supports the short anonymous function syntax, my task is admittedly a _lot_ easier, as I _won't_ be transpiling the code (actually it won't change at all, just the dependency).

But yeah, back to transpiling...

_If_ it was to be done, ideally you'd isolate it as a dependency, then other IDE's can take advantage. There are actually already tools to do stuff like this Metalua etc. which is actually what MoonSharp based this short anonymous function syntax on. I suspect they're all "one direction transpilation" though.

There's also pretty sweet stuff like [TypeScriptToLua](https://github.com/TypeScriptToLua/TypeScriptToLua).

Whilst it's a somewhat artificial constraint, we do generally want to be able reverse everything we do; as a result every little addition is going to feel pretty convoluted. Personally, I wouldn't be bothered doing it; but that's obviously a very subjective opinion.
