### ISSUE TITLE
`require` breaks on dot-separated file path

### ISSUE THREAD

**Issue by kevin-d-omara** [Berserk-Games/atom-tabletopsimulator-lua#114]
## Problem
The new `require` syntax doesn't work for dot-separated file paths, i.e. `require("folder.filename")`.

However, standard Lua allows for both dot-separated and slash-separated paths:
```lua
require("folder.filename")
require("folder/filename")
```

Here's a screenshot of the error I get when hitting "Save and Play" in Atom:
<img width="960" alt="error-when-save-and-play" src="https://user-images.githubusercontent.com/11803661/79708404-2eba4d00-8274-11ea-8039-95fac60ff6b2.png">

The error says:
```
Unable to process Global.-1.ttslua
Could not resolve module 'nested_module.value_of_pi' required by '__root' at 2:9
```

## How to Reproduce the Problem
To reproduce the problem, create this file in your TTS Atom Workspace:
```
project-root/
    nested_module/
        value_of_pi.ttslua
```

WIth the contents of **value_of_pi.ttslua**:
```lua
return 3.14159265359
```

Then paste this into the **global script** (Global.-1.ttslua)
```lua
function onLoad()
    PI = require("nested_module.value_of_pi")
    print("The value of PI is: " .. tostring(PI))
end
```

Then hit **Save and Play** in Atom. You'll be presented with the error shown in the earlier screenshot.

**Comment by Benjamin-Dobell** [comment]
Technically, Lua has no concept of directories at all, because ANSI C has no concept of directories. Whilst it's convention to use dots for LuaRocks, the Rocks themselves are actually still a flat hierarchy, they don't contain any directories.

LuaRocks has some bundling behaviour that can be setup to take directories and convert them to dot-separated paths, but the libraries as consumed on your disk are always just files with dots in their names.

Because TTS only runs on computers that have a concept of directories, unlike Lua which runs on embedded ANSI C systems, we're specifically supporting directories. `/` has been chosen as the path separator. _However_, if you want, you still ought to be able to `require` flat libraries by their dot-separated path names. `require` just won't traverse directories using dots.

**Comment by kevin-d-omara** [comment]
Thanks for explaining about ANSI C and LuaRocks. I didn't realize LuaRocks are bundled as a flat hierarchy. I was able to confirm that by [reading the docs](https://github.com/luarocks/luarocks/wiki/Creating-a-rock#building-a-module) (see `apricot` vs `apricot.seeds`). I'm glad LuaRocks will work fine in TTS with the dot notation.

Since ANSI C has no concept of directories, I don't understand why the dot separated notation works fine on my computer (through IntelliJ w/ [EmmyLua](https://github.com/EmmyLua/IntelliJ-EmmyLua)) and also online through Repl.it ([try out the example here](https://repl.it/repls/WideLivelyDistributionsoftware)). Do you know why?

I found a [discussion on require() notation](https://forums.coronalabs.com/topic/63358-so-why-corona-sdk-insists-on-using-dot-instead-of-slash-for-require/) which points to the [Lua source code](https://www.lua.org/source/5.2/loadlib.c.html), where Lua replaces `.` with `dirsep` (the platform dependent directory separator). Just search for `name = luaL_gsub(L, name, sep, dirsep);  /* replace it by 'dirsep' */`. You can trace the call of `searchpath` all the way to `searcher_Lua`, `searcher_C`, and `searcher_Croot`. These names seem related to `LUA_PATH` and `LUA_CPATH`, which are the paths where Lua searches when loading files with `require()`. So from this high level reading, it looks like Lua is aware of directories.

**Comment by Benjamin-Dobell** [comment]
I must admit I was unaware of this gsub behaviour in Lua. It's a little bit odd that https://www.lua.org/pil/8.1.html claims:

> ANSI C (the abstract platform where Lua runs) does not have the concept of directories

but then Lua proceeds to know about platform-dependent directory separators. However, based on this information, this seems like a perfectly reasonable change request.

I've opened an issue against [luabundle](https://github.com/Benjamin-Dobell/luabundle) which is the underlying library used by Atom to support `require`.

This issue here is still valid though, as once `luabundle` is updated, this plugin will need to update its version of `luabundle`.

**Comment by kevin-d-omara** [comment]
Thanks for opening up an issue against luabundle.
