### ISSUE TITLE
Closes any previously open files when TTS opens

### ISSUE THREAD

**Issue by adracko** [Berserk-Games/atom-tabletopsimulator-lua#51]
There have been a few times I was working on a file then was invited into a TTS game. I'd forget to save and  this plugin would auto close without saving any previously open files. Infuriating to say the least.

**Comment by onelivesleft** [comment]
By default the plugin is working on a temp file created by TTS; when you load something else in TTS this file is replaced.  A better technique (which perhaps should be documented better) is to use the #include command* so that your codebase is located elsewhere on your hard disk, and isn't just kept inside the TTS save file.  See: http://blog.onelivesleft.com/2017/08/atom-tabletop-simulator-package.html

* you have to enable it in the package settings

Since you can locate your files anywhere on your hard disk with this, you can easily commit them to source control or otherwise back them up.
